### PR TITLE
Quantum update bc someone finally asked for it

### LINKED ISSUE #598: Quantum states aren't locked by photos
### What Happened?

They are defying lore-accurate physics and therefore not god-honoring

### What was supposed to happen?

Be locked into that state while observed by photo

### Platform

None

### Mods

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by JohnCorby**
## Major features
-

## Minor features
-

## Improvements
-

## Bug fixes
- QuantumGroups of type "states" no longer ignore probe snapshots taken of them (resolves #598)

### CODE REVIEW

**Comment by MegaPiggy** [comment]
that's a lot of updates lol

**Comment by FreezeDriedMangos** [comment]
> that's a lot of updates lol

lol I have no idea how that ended up in my history for this branch

**Review by FreezeDriedMangos — APPROVED** [review]
looks good, especially that fix on the quantum objects, nice work whoever did that

**Comment by JohnCorby** [comment]
tested by me and clay with examples so we chillin

**Pull request merged**
