### PR TITLE
Fix the what bug again

### PR DESCRIPTION
**Pull request by JohnCorby**
## Bug fixes
- Log an error when trying to orbit a body that doesn't have a gravity volume.

### CODE REVIEW

**Comment by JohnCorby** [comment]
- [ ] test examples

**Review by MegaPiggy — APPROVED** [review]

**Comment by xen-42** [comment]
hey dum dum update the manifest version

**Comment by xen-42** [comment]
wait wtf its updated!!!

**Review by xen-42 — APPROVED** [review]
lgtm

**Pull request merged**
