### PR TITLE
Add destroy patches

### PR DESCRIPTION
**Pull request by MegaPiggy**
## Major features
-

## Minor features
-

## Improvements
-

## Bug fixes
-

### CODE REVIEW

**Review by JohnCorby — APPROVED** [review]
probably wanna do #573 in here too and then i gotta test :(

**Review by JohnCorby — CHANGES_REQUESTED** [review]
i clicked the wrong button lol

**Comment by MegaPiggy** [comment]
Narp!

**Comment by MegaPiggy** [comment]
supposedly kills qsb compat (wont even change the title screen)
so I am closing this

**Pull request closed without merging**
