### PR TITLE
Better vessel warp

### PR DESCRIPTION
**Pull request by MegaPiggy**
## Improvements

- Relative spawning when warping with vessel just like vanilla
- No more wake up effects for vessel warping

## Bug fixes

- Fixed nomai lamps on custom vessel looking like they are off
- Fixed broken black and white holes on custom vessel
- Fixed vessel coordinate orb not unlocking on start

### CODE REVIEW

**Comment by MegaPiggy** [comment]
https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/34462599/b5708992-3352-48e9-8412-23949052152d

**Comment by MegaPiggy** [comment]
Reverse

https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/34462599/0811a7c1-93ea-459b-b17e-4d3d0a8aecab

**Comment by MegaPiggy** [comment]
Eye

https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/34462599/01ac9ad5-61ad-4239-802b-1b91b8240921

**Review by xen-42 — APPROVED** [review]
lgtm

**Pull request merged**
