### PR TITLE
Fixes for QSB

### PR DESCRIPTION
**Pull request by misternebula**
- [x] Use `LoadScene` instead of `LoadSceneImmediate` because that doesn't call OnPreSceneLoad
  - [x] test codec (has stuff at eye)
  - [x] test dreamstalker (overrides the nh eye stuff)
    - [x] eye stuff doesnt spawn, seems to not go over to eye scene (when using QSB) (qsb issue made)
    - [x] test it without qsb too (works fine)
- [x] Name ship warp drive dialogue objects so QSB can avoid them.

[check for issues in QSB PR](https://github.com/qsb-dev/quantum-space-buddies/pull/668)

### CODE REVIEW

**Comment by Bwc9876** [comment]
:nerd_face:

**Comment by xen-42** [comment]
so this is done right? the dreamstalker stuff is dreamstalker not nh so i dont care!

**Comment by JohnCorby** [comment]
waiting on qsb pr to be completed

**Review by JohnCorby — APPROVED** [review]

**Comment by JohnCorby** [comment]
test before final merge please

**Comment by JohnCorby** [comment]
actually now with dreamstalker it just refuses to work and throws a hash error. looks like one side is generating eye stuff while the other isnt. probably something to do with host stuff being silly

**Comment by JohnCorby** [comment]
tested a little bit, things seem to still work as before

**Pull request merged**
