### PR TITLE
Spawn in bramble

### PR DESCRIPTION
**Pull request by xen-42**
## Improvements

- Allow spawning inside Bramble dimensions (base game spawn point does not work yet)

### CODE REVIEW

**Comment by JohnCorby** [comment]
stock planets does not work. i dont spawn where i say to spawn

**Comment by xen-42** [comment]
ok cool so we just say that that doesnt work

**Comment by xen-42** [comment]
actually why wouldnt that work, we can set spawn point in the base system to other planets, ok we should probably make that work then

**Review by MegaPiggy — APPROVED** [review]

**Comment by JohnCorby** [comment]
will do stock planets later

**Pull request merged**
