### PR TITLE
Remake Docs In Astro

### PR DESCRIPTION
**Pull request by Bwc9876**
Remade the documentation site in Astro

Preview Link: https://nh-docs-temp.surge.sh/

Content is pretty much untouched except for:
- FAQ is gone (no one uses it)
- So is the config editor page
- Reading schemas page is gone
- Schemas are now more granular, everything isn't flattened and put onto one page (terrible for accessibility, SEO, and performance)

(Actual) Search will work straight out of the box (starlight uses PageFind)

TODO:
- [x] Use Astro v3 Images instead of putting stuff in `public/`
- [x] Spacing on schema pages needs adjusting
- [x] Once-over on links and such, *schema links have changed*
- [x] Update workflows
- [x] Make an announcement asking for feedback (lest the addon devs revolt)

### CODE REVIEW

**Comment by JohnCorby** [comment]
waiting for starlight update

**Comment by MegaPiggy** [comment]
RIP FAQ, config editor page, and reading schemas page

**Comment by Bwc9876** [comment]
> RIP FAQ, config editor page, reading schemas page, and secret page. Why were they removed?

FAQ was filled with outdated/joke/just not very good info
Config editor is DEAD
Reading schemas is redundant, especially with new schema pages
Secret page I uh just didn't feel like adding it to robots.txt and stuff

**Comment by JohnCorby** [comment]
is this still blocked on starlight? or is there another issue now

**Comment by Bwc9876** [comment]
Starlight's prolly not gonna add the feature, which means I'm gonna have to rewrite some stuff, which I don't really have bandwidth for rn

**Review by JohnCorby — APPROVED** [review]

**Pull request merged**
