### PR TITLE
Consistency in Planet/System Config Name

### PR DESCRIPTION
**Pull request by JohnCorby**
## Improvements
- Consistency between planet and system name: use config value, otherwise use file name

### CODE REVIEW

**Comment by MegaPiggy** [comment]
Lie to them! That was added so that when people are editing their config, their IDE doesn't go `"semiMajorAxis": 0` and instead goes `"semiMajorAxis": 5000`.

**Comment by Bwc9876** [comment]
Yeah nh doesn't use defaults in the way json schema intended bc we're silly bleh.

**Comment by JohnCorby** [comment]
can we not just uh specify that default as an attribute tho?
like we do with everything else?
i feel uneasy lying to addon devs

**Comment by JohnCorby** [comment]
> Yeah nh doesn't use defaults in the way json schema intended bc we're silly bleh.

**Comment by xen-42** [comment]
ok dont lie to them!

**Pull request merged**
