### PR TITLE
Global music module

### LINKED ISSUE #894: ability to add custom end times
### Feature

since we have the ability to have custom travel music, why not custom end times for other systems? i'm not sure if this is necessary, but you could consider a custom final voyage as well.

### Context

_No response_

### PR DESCRIPTION
**Pull request by MegaPiggy**
## Major features

-  Added `GlobalMusic` module to system config (change end times, bramble dimension, and final end times music) (Resolves #894)

## Bug fixes

- Fixed global bramble music not playing because all dimensions have an ambient audio volume

### CODE REVIEW

**Comment by xen-42** [comment]
I'd want to test this with other music-changing mods like Light Bramble and potentially Outsider before merging

**Comment by MegaPiggy** [comment]
> I'd want to test this with other music-changing mods like Light Bramble and potentially Outsider before merging

true... Light Bramble is probably fine but Outsider maybe not

**Comment by MegaPiggy** [comment]
ok so outsider is fine, it just doesn't use the custom end times start time here which isn't a big deal since it is just unmixing.

https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/blob/17f35bb3ebd081238ec83c226592f756c960c1db/TheOutsider/OuterWildsHandling/OWPatches.cs#L591

**Comment by MegaPiggy** [comment]
light bramble is fine too. custom music does override the non spooky music though.

**Review by xen-42 — APPROVED** [review]

**Pull request merged**
