### PR TITLE
Allow parenting of gravity cannons and shuttles to details

### PR DESCRIPTION
**Pull request by MegaPiggy**
## Improvements

- Can now parent gravity cannons and shuttles to details

### CODE REVIEW

**Review by JohnCorby — CHANGES_REQUESTED** [review]
but now you cant parent details to gravity cannons!

**Comment by MegaPiggy** [comment]
you either can or cannot parent due to the order.
I think it is more important to be able parent the cannon to a detail instead. Especially for something like a unity asset.

**Comment by xen-42** [comment]
I feel like people might want to attach details to shuttles. Is there any better way we can do this stuff, maybe if a thing being parented cant find the parent it waits until everything else is done?

**Review by JohnCorby — APPROVED** [review]

**Comment by xen-42** [comment]
I'm saying no to this because putting a detail on a shuttle (and allowing that detail to fly off with the shuttle) seems more important than putting a shuttle on top of a detail.  I'd rather have us making a queuing system where the order of all props being made can be entirely shifted base on what wants to be parented to what. Probably anything that can't find its parent, we keep a list of all those and run another pass on those items and their builders.

**Pull request closed without merging**
